apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-app-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  storageClassName: manual

