apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: kushagraag/threetierwebapp-backend:latest
        ports:
        - containerPort: 8080

